### ISSUE TITLE
Plans for theory combination?

### ISSUE THREAD

**Issue by leonardoalt** [uuverifiers/eldarica#33]
Hi there :)
I just tried Eldarica on one of my benchmarks and got

```
Theories: ADT(tx_type), ADT(bytes_tuple), SimpleArray(1)
(error "Combination of theories is not supported")
```

Are there any plans to support that?
Here's the smt2 file if anyone is interested:
https://gist.github.com/leonardoalt/d797eca839f14bb1997de7c5a6496a83

**Comment by pruemmer** [comment]
Hi Leonardo,

yes, we are working on a new array solver that will be able to handle this combination as well. Should have something running by the next CHC-COMP ;-)

Best wishes, Philipp

**Comment by leonardoalt** [comment]
That's great! Thanks @pruemmer

**Comment by pruemmer** [comment]
The last master should now support this combination (arrays + ADTs), although the functionality is not much tested yet.

**Comment by leonardoalt** [comment]
@pruemmer awesome! I just tried it on the sample I posted earlier and it works perfectly.
I'll try it on the rest of my benchmarks next week.
