### ISSUE TITLE
(error "Value too big to be converted to int")

### ISSUE THREAD

**Issue by leonardoalt** [uuverifiers/eldarica#34]
https://gist.github.com/leonardoalt/3f50d06a1c7cac086fe01c36a025a805
Version: nightly

The benchmark above is unsat. When I use `-cex` (or `-dotCEX`) I get the error
`(error "Value too big to be converted to int")`.
My model has integers up to 2^256-1, so I'm guessing that's the issue.

**Comment by pruemmer** [comment]
This should now be fixed; you need to run "sbt clean" to get the newest
library versions. Thanks for the report!

**Comment by leonardoalt** [comment]
Thanks @pruemmer !
