### ISSUE TITLE
Arrays in Prolog?

### ISSUE THREAD

**Issue by leonardoalt** [uuverifiers/eldarica#36]
Quick question, is it possible to somehow represent in a Prolog input what would be an Array in smtlib?
Thanks!

**Comment by pruemmer** [comment]
At the moment our Prolog frontend does not support arrays (nor ADTs). We
are looking for volunteers to rewrite the frontend ;-)

**Comment by leonardoalt** [comment]
Not sure how much I would be able to help there ;)
Thanks for the answer @pruemmer
