### ISSUE TITLE
(error "Invalid expression UnaryExpression(ArrayConstOp(),NumericalConst(0))")

### ISSUE THREAD

**Issue by leonardoalt** [uuverifiers/eldarica#37]
Sample: https://gist.github.com/leonardoalt/e0181bed3c520c2df47f489ff171fa6b
Command: `eld -abstract:off -ssol`
It correctly answers SAT, and returns the title error while producing the solution.

**Comment by pruemmer** [comment]
Thanks for the bug report! This was a missing case in the code
outputting solutions, and should now be fixed. (There might still be one
or the other bug in the pretty-printer for bit-vectors though ...)

**Comment by leonardoalt** [comment]
Thanks @pruemmer !
