### ISSUE TITLE
(error "Invalid expression UnaryExpression(Int2BV(64),Variable(_9,Some(9)))")

### ISSUE THREAD

**Issue by leonardoalt** [uuverifiers/eldarica#38]
Sample: https://gist.github.com/leonardoalt/21598d1931cbe98a0c3ae64a1df1fded
Command: `eld -abstract:off -ssol`
Like the other issue, it correctly answers SAT (the two samples are very similar) but gives the error when computing the solution.

**Comment by pruemmer** [comment]
Same here
