### ISSUE TITLE
question about Unrecoverable Syntax Error

### ISSUE THREAD

**Issue by izlatkin** [uuverifiers/eldarica#41]
Hello, 

Does eldarica support only some particular smt-lib formates / has partially support?

For example, it returns "Unrecoverable Syntax Error"
for every smt2 files generated by https://github.com/seahorn/seahorn
or for the majority of the files from https://github.com/grigoryfedyukovich/aeval/tree/student-projects/bench_horn

Are declare-rel, declare-var supported?

thank you

**Comment by pruemmer** [comment]
Eldarica currently only supports standard SMT-LIB input. The operations
declare-rel, declare-var are a Z3 extension for their fixedpoint engine,
and not part of the standard language.

You can use the chc-tools to convert between those different formats:
https://github.com/chc-comp/chc-tools

**Comment by izlatkin** [comment]
How exactly I can do this? It is not really clear from readme how to launch the tool.

**Comment by pruemmer** [comment]
I cannot comment on this unfortunately. You will need to download and
compile the tool first, but concerning the use of the tool it is best if
you create as issue in the chc-tools repository!
