### ISSUE TITLE
Weird hanging issue

### ISSUE THREAD

**Issue by leonardoalt** [uuverifiers/eldarica#43]
Hi, not sure this is going to be reproducible, but let's see.
I have this large benchmark: https://raw.githubusercontent.com/leonardoalt/chc_benchmarks_solidity/main/has_cex.smt2
It is unsat.
When I run Eldarica with `-cex` I get the solution and cex after 1 min, but if I add `-t` it hangs.
Commands:

```
$ time eld -horn -abstract:off -cex has_cex.smt2
unsat
<entire_cex>
eld -horn -abstract:off -cex has_cex.smt2  96.14s user 1.17s system 195% cpu 49.832 total
```

```
$ time eld -horn -abstract:off -t:300 -cex has_cex.smt2
```
Here it hangs, I've let it run for over 20 min.

**Comment by leonardoalt** [comment]
Sometimes it also hangs in counterexample generation also without `-t`, so that doesn't seem to be related.
Using verbosity 3, this is the last I see before hanging:

```
...
(17and/0or) .. ... failed, counterexample is genuine

--------------------------------- Statistics -----------------------------------
CEGAR iterations:                                      17
Total CEGAR time (ms):                                 10901
Setup time (ms):                                       5511
Final number of abstract states:                       28
Final number of matched abstract states:               28
Final number of abstract edges:                        63
Number of generated predicates:                        16
Average predicate size (# of sub-formulas):            1.00
Predicate generation time (ms):                        2043
Number of implication checks:                          425

Number of implication checks (setup):                  306
Number of implication checks (positive):               77
Number of implication checks (negative):               42
Time for implication checks (setup, ms):               2795
Time for implication checks (positive, ms):            0
Time for implication checks (negative, ms):            109
--------------------------------------------------------------------------------
```

**Comment by pruemmer** [comment]
Thanks, good catch!

I'm looking into this issue, and am quite sure that it is completely
independent of the -t option. The underlying cause seems to be some
non-determinism in the array solver, which sometimes leads to timeouts
and sometimes does not ...

**Comment by pruemmer** [comment]
This problem should be fixed in the latest version (be sure to use also
the latest version of the Princess library).

**Comment by leonardoalt** [comment]
Awesome!
I usually just download the latest nightly from the README page, that should have everything shipped together, right?
Thanks!

**Comment by leonardoalt** [comment]
I confirm that the latest nightly fixes it.
