### ISSUE TITLE
(error "Failed to reconstruct array model")

### ISSUE THREAD

**Issue by leonardoalt** [uuverifiers/eldarica#44]
Using the new nightly on the benchmark below (which should be unsat) I get `(error "Failed to reconstruct array model")`
https://raw.githubusercontent.com/leonardoalt/chc_benchmarks_solidity/main/array.smt2

**Comment by pruemmer** [comment]
This should be fixed in the latest version!

Thanks for the bug reports, they were very useful for located problems
with the new array solver, and fixing them ...

**Comment by leonardoalt** [comment]
Hi @pruemmer , it looks like the latest nightly isn't shipping the `target` folder with the jar

**Comment by leonardoalt** [comment]
Ah yes, confirm that it's there and solves the issue!
Thanks!
