### ISSUE TITLE
Specific version commit in binary

### ISSUE THREAD

**Issue by leonardoalt** [uuverifiers/eldarica#45]
It would be great for reproducibility if the `eld` binary could output the commit hash (or the first bytes, git style) with `-v` or something.
My current issue is I had a version of Eldarica that worked on some benchmarks but I have a bunch of Eldarica versions on my machine (I use nightlies a lot) and now I can't remember which it was :smiling_face_with_tear:   . Granted, my fault, but commit hashes would help in general I think

**Comment by pruemmer** [comment]
Thanks for the bug report! In fact we used to add the date of the
nightly build in the binary, but the script doing that apparently
stopped working a while ago, and nobody noticed. I have fixed this now;
from tomorrow, when you run ./eld -h the date of the build should be
listed in the first line.

**Comment by leonardoalt** [comment]
Awesome! I confirm it is working now. Thanks!
