### ISSUE TITLE
(error "Predicate generation failed")

### ISSUE THREAD

**Issue by leonardoalt** [uuverifiers/eldarica#46]
Benchmark: https://gist.github.com/leonardoalt/40a9f094247f45f415b8bb9b9b3b1ab2
Using Eldarica's nightly from 15/05.

It's the first time I encounter this error so wanted to ask about it.
Please feel free to close if it's intended.

**Comment by pruemmer** [comment]
This is the same error as the old one about unsupported quantifiers in
predicates!
