### ISSUE TITLE
eldarica returns UNSAT for SAT instance

### ISSUE THREAD

**Issue by kensingRichardt** [uuverifiers/eldarica#57]
Hello everyone,

it seems that eldarica returns erroneously UNSAT for the following SMT-Code:
```
(declare-datatype f_type ((cons (b Int))))
(declare-datatype abi_type ((a)))

(declare-fun pred1 (Int abi_type f_type f_type) Bool)

(assert (forall ((l abi_type) (p f_type)) (pred1 0 l p p)))
(assert (forall ((m abi_type) (o Int) (aa f_type) (ab f_type))
  (=> (pred1 o m aa ab) (or (exists ((var0 abi_type)) (not (= var0 a))) (and (= ab aa) (= o 0)))))
)

(check-sat)
```
I get
```
$ ~/eldarica/eld  sat.smt2 
unsat
```
A model is given by
`(define-fun pred1 ((A Int) (B abi_type) (C f_type) (D f_type)) Bool (and (= D C) (= A 0)))`
Eldarica is even able to verify this model by returning "sat" when replacing the `(declare-fun ...)` statement with the line above.

**Comment by pruemmer** [comment]
Thank you for the bug report! I suspect we do not handle the existential 
quantifier in the last clause correctly, I'm looking into it!

**Comment by pruemmer** [comment]
This should be working correctly now!

**Comment by kensingRichardt** [comment]
Thanks for fixing it!
