### ISSUE TITLE
semantics of _size operator

### ISSUE THREAD

**Issue by kensingRichardt** [uuverifiers/eldarica#58]
Hello everyone,

it seems that eldarica returns erroneously UNSAT for the following SMT-Code:
```
(declare-datatypes ((C_dtp 0)) (((cons_c (n Int)))))
(declare-datatypes ((B_dtp 0)) (((cons_b (elem C_dtp)))))

(assert
  (=
    (_size (cons_b (cons_c 0)))
    2
  )
)

(check-sat)
```
I read in the docu that _size is supposed to return the number of constructors used in a term, so that would be exactly 2 for `(cons_b (cons_c 0))`, which is why I expected eldarica to return SAT.

**Comment by pruemmer** [comment]
This is the intended semantics of `_size`, although I agree that the 
behaviour is slightly confusing. Each data-type definition (all 
data-types declared using a single `declare-datatype` or 
`declare-datatypes`) comes with its own `_size` operator, which will 
only count the constructors that belong to that definition. The term 
`(cons_b (cons_c 0))` therefore only contains one constructor 
(`cons_b`), as well as one alien sub-term `(cons_c 0)` that `_size` does 
not look into.

If you modify your example to declare both data-types with a single 
definition

```
(declare-datatypes ( (C_dtp 0) (B_dtp 0) )
       ( ( (cons_c (n Int) ) )
         ( (cons_b (elem C_dtp)) ) ))
```

then the benchmark becomes sat.
