### ISSUE TITLE
Supported SMT-LIB version 

### ISSUE THREAD

**Issue by fgs15** [uuverifiers/eldarica#70]
Eldarica, version 2.1, reports the error: 

Syntax Error, trying to recover and continue parse...
(error "At line 1, near " " inv  (Int" ": Unrecoverable Syntax Error")

when solving CHC in [aeval-benchmarks](https://github.com/chc-comp/aeval-benchmarks/blob/main/multi-phase/s_split_54.smt2).

I notice that many CHC solvers, such as FreqHorn, support SMT-LIB2 version in the format like "(declare-rel inv (Int Int Int))", and "(rule (=>..))". Also, the CHC-COMP2024 selects some benchmarks from aeval-benchmarks. So, how can I solve CHC in this format using Eldarica? I have just started learning CHC solving.

**Comment by pruemmer** [comment]
Eldarica does unfortunately not support this "rules" dialect of
SMT-LIB. It is possible to convert files in the "rules" version to
standard SMT-LIB using the chc-tools,

https://github.com/chc-comp/chc-tools
https://github.com/chc-comp/scripts

(I don't remember exactly which of the scripts is the right one though)

**Comment by fgs15** [comment]
Thank you for your reply!
