### ISSUE TITLE
Unexpected result 'UNSAT' for sat-formula

### ISSUE THREAD

**Issue by kensingRichardt** [uuverifiers/eldarica#71]
Hello again,

I found a case where eldarica returns unexpectedly UNSAT:
```
(declare-datatypes ((k 0)) (((k (y Int)))))
(declare-datatypes ((e 0)) (((e (f (Array Int k))))))
(declare-datatypes ((g 0)) (((g (h (Array Int e))))))
(declare-fun j (g) Bool)

(assert (forall ((r g))
    (=>  (> (y (select (f (select (h r) 0)) 0)) 0) (j r))))
   

(assert (forall ((r g))
    (=  (> (y (select (f (select (h r) 0)) 0)) 0) (j r))))
    
(check-sat)
```
Here is how I invoked eldarica:
```
$ ~/eldarica/eld -cloneArrays sat.smt2 
unsat
```
When omitting option `-cloneArrays ` we get `sat` as expected. 
I did not expect that this option changes the sat-result or is this intended behavior?

**Comment by pruemmer** [comment]
That was a good observation! The option -cloneArrays is not well tested 
yet (and a bit experimental); but indeed this transformation was not 
compatible with ADTs occurring in clauses. This should be fixed in the 
latest commit.

**Comment by kensingRichardt** [comment]
Thanks for fixing this!
