### ISSUE TITLE
Meaning of `Inconclusive`

### ISSUE THREAD

**Issue by cocreature** [uuverifiers/eldarica#8]
On the following example
```
(set-logic HORN)
(declare-fun
   INV_MAIN_0
   (Int
    Int)
   Bool)
(assert
 (forall
  ((HEAP$1 (Array Int Int))
   (i1 Int))
  (INV_MAIN_0 i1 (select HEAP$1 i1))))
(assert
 (forall
  ((i1 Int)
   (heap1 Int))
  (=>
   (INV_MAIN_0 i1 heap1)
   true)))
(check-sat)
(get-model)
```
I get a MatchError `Inconclusive`. Leaving aside the fact that this should probably be catched and turned into a nice error message, I can’t figure out why that’s the case. Any ideas?

**Comment by pruemmer** [comment]
Thanks, this should be fixed with the last commit. The example is unusual in the sense that you quantify over arrays, which is not handled in a complete way in all cases by the current implementation. But of course this should not lead to an exception.

Philipp

**Comment by cocreature** [comment]
Thanks!
